<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var Magento\Customer\Block\Account\Customer $block */
?>

<li class="customer-welcome">
    <span class="customer-name"
          role="link"
          tabindex="0"
          data-mage-init='{"dropdown":{}}'
          data-toggle="dropdown"
          data-trigger-keypress-button="true"
          data-bind="scope: 'customer'">
        <button type="button"
                class="action switch"
                tabindex="-1"
                data-action="customer-menu-toggle">
            <span><?= $block->escapeHtml(__('Change')) ?></span>
        </button>
    </span>
    <?php if ($block->customerLoggedIn()) { ?>
    <script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "customer": {
                        "component": "Magento_Customer/js/view/customer"
                    }
                }
            }
        }
    }
    </script> 
    <?php } ?> 
    <?php if ($block->getChildHtml()) :?>
        <div class="customer-menu" data-target="dropdown">
            <?php if ($block->customerLoggedIn()) { ?>
                <?= $block->getChildHtml() ?>
            <?php }else{ ?>
                <ul class="header links">
                    <li>
                        <a href="<?= $this->getUrl('customer/account/login') ?>"><?= __('Sign in'); ?></a>
                    </li>
                    <li>
                     <a id="recommendation_link" href="javascript:void(0);"><?= __('Get Recommendation'); ?></a>
                    </li>
                </ul>
            <?php } ?>
        </div>
    <?php endif; ?>
</li>

