<?php 
$refererUrl = $block->getRefererUrl();
$resultUrl = $this->getUrl('mphyperlocal/result/collection');
$vendorUrl = $this->getUrl('mphyperlocal/vendor/collection');
$guidetoolUrl = $this->getUrl('get-recommendation');
$baseUrl = $block->getBaseUrl();
?>
<script type="text/javascript">
require([
    'jquery',
    'mage/mage'
], function($){
	var refererUrl = '<?php echo $refererUrl ?>';
	var resultUrl = '<?php echo $resultUrl ?>';
	var vendorUrl = '<?php echo $vendorUrl ?>';
	var guidetoolUrl = '<?php echo $guidetoolUrl ?>';
	var baseUrl = '<?php echo $baseUrl ?>';
	
	var selectedAttrs = {};
    jQuery(".cont-checkbox").click(function () {

        jQuery(this).parent().find(".cont-checkbox").each(function(){
            jQuery(this).removeClass("is_active");
        });
        
        jQuery(this).addClass("is_active"); 
        
        var elementId = jQuery(this).find('input[type=radio]').attr('id');
        var elementArray = elementId.split("-");
        var array_key = elementArray[2];
        var tabId = elementArray[0];
        selectedAttrs['step'+array_key] = jQuery(this).find('input[type=radio]').val();
        //selectedAttrs[jQuery(this).find('input[type=radio]').attr('name')] = jQuery(this).find('input[type=radio]').val();

        if(jQuery(this).parents('.card-sec').is(':last-child')){
            //selectedAttrs['tab'] = tabId;
            var url_string = param(selectedAttrs);
			refererUrl = refererUrl.endsWith('/') ? refererUrl.slice(0, -1) : refererUrl;
			guidetoolUrl = guidetoolUrl.endsWith('/') ? guidetoolUrl.slice(0, -1) : guidetoolUrl;
			var finalUrl = '';
			if(refererUrl == guidetoolUrl){
				finalUrl = vendorUrl;
			}else{
				finalUrl = resultUrl;
			}
            window.location.href = finalUrl+"?"+url_string;
        }else{
        	window.setTimeout((function(){
			    jQuery(this).parents('.card-sec').find(".next.action-button.nxt-btn").click();
			}).bind(this), 150);
        }
        //return false;
    });
	
	function param(object){
        var parameters = [];
        for (var property in object) {
            if (object.hasOwnProperty(property)) {
                parameters.push(encodeURI(property + '=' + object[property]));
            }
        }
        return parameters.join('&');
    }
	
	jQuery(".previous-first").click(function(){
		if(refererUrl == ''){
			refererUrl = baseUrl;
		}
        window.location.href = refererUrl;
    });
});
</script>