
   <div class="col tpm">
      <div class="banner_wrap hover-zoom"><a href="<?= $this->getUrl('shopby') ?>#tab1"><img src="<?= $this->getViewFileUrl("images/Recommendation-Activity.png") ?>" alt="activity"> </a></div>
   </div>
   <div class="col">
      <div class="banner_wrap hover-zoom"><a href="<?= $this->getUrl('shopby') ?>#tab2"><img src="<?= $this->getViewFileUrl("images/Recommendation-Strain-200x200.png") ?>" alt="strain"></a></div>
   </div>
   <div class="col">
      <div class="banner_wrap hover-zoom"><a href="<?= $this->getUrl('shopby') ?>#tab3"><img src="<?= $this->getViewFileUrl("images/Recommendation-Mood.png") ?>" alt="mood"></a></div>
   </div>
   <div class="col">
      <div class="banner_wrap hover-zoom"><a href="<?= $this->getUrl('shopby') ?>#tab4"><img src="<?= $this->getViewFileUrl("images/Recommendation-.png") ?>" alt="recommendation"></a></div>
   </div>
   <div class="col">
      <div class="banner_wrap hover-zoom"><a href="<?= $this->getUrl('shopby') ?>#tab5"><img src="<?= $this->getViewFileUrl("images/Recommendation-Surprise1.png") ?>" alt="surprise"></a></div>
   </div>
